import type { Metadata } from "next";
import "./globals.css";

// redux provider
import StoreProvider from "@/redux/StoreProvider";

// font
import { poppins } from "./fonts";

export const metadata: Metadata = {
  title: "বাজার - আপনার নিত্যপ্রয়োজনের সঙ্গি",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        cz-shortcut-listen="false"
        className={`${poppins.className} antialiased`}
      >
        <StoreProvider> {children}</StoreProvider>
      </body>
    </html>
  );
}
